site_name: Cutie City Guide
site_url: https://guide.cutie.city
site_description: A guidebook for Cutie City and the wider Fediverse.
site_author: Nuztalgia
copyright: Copyright &copy; 2023 Nuztalgia
repo_name: CutieCity/guide
repo_url: https://github.com/CutieCity/guide

nav:
  - Home: index.md
  - Cutie City:
      - Code of Conduct: cutie-city/code-of-conduct.md
      - Custom Emoji: cutie-city/custom-emoji.md
      - Custom Themes: cutie-city/custom-themes.md
      - Server Blocklist: cutie-city/server-blocklist.md
  - The Fediverse:
      - Fedi Etiquette: the-fediverse/fedi-etiquette.md
      - Migrating Servers: the-fediverse/migrating-servers.md
  - Self-Hosting:
      - Object Storage: self-hosting/object-storage.md
      - Development Setup: self-hosting/development-setup.md

watch:
  - overrides/

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  icon:
    logo: material/map-search
    repo: fontawesome/brands/github
    admonition:
      note: material/note-search-outline
      abstract: material/list-box-outline
      info: material/information-outline
      tip: material/lightbulb-on-outline
      success: material/check-circle-outline
      question: material/help-circle-outline
      warning: material/alert-rhombus-outline
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.sections

extra:
  social:
    - icon: material/mastodon
      link: https://cutie.city
      name: Check out our Mastodon instance!
    - icon: material/github
      link: https://github.com/CutieCity
      name: Visit our organization on GitHub!
    - icon: simple/kofi
      link: https://ko-fi.com/nuztalgia
      name: Support Nuztalgia on Ko-fi!

extra_css:
  - stylesheets/global.css
  - stylesheets/material.css
  - stylesheets/custom-emoji.css

extra_javascript:
  - javascripts/global.js
  - javascripts/custom-emoji.js
  - javascripts/migrating-servers.js

plugins:
  - git-committers:
      enabled: !ENV [ENABLE_GIT_PLUGINS, false]
      repository: CutieCity/guide
      branch: main
  - git-revision-date-localized:
      enabled: !ENV [ENABLE_GIT_PLUGINS, false]
      type: timeago
      locale: en
      exclude:
        - index.md
  - glightbox:
      skip_classes:
        - cutiemoji
        - no-lightbox
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:cutiecityguide.emoji_index
      emoji_generator: !!python/name:cutiecityguide.emoji_generator
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - tables
  - toc:
      permalink: ☍
      permalink_title: Copy link to this section
      title: Table of Contents
